# Copyright Notice:
# Copyright 2025 DMTF. All rights reserved.
# License: BSD 3-Clause License. For full text see link:
#   https://github.com/DMTF/PMCI-Protocol-Validator/blob/main/LICENSE.md
##############################################################################
#  File Abstract:
#  Definitions from DSP0249 "Platform Level Data Model (PLDM) State Set
# #Specification", Version: 1.3.0
##############################################################################

""" Table 15 - Entity ID Codes """

entity_id_codes = {
    0: "Unspecified",
    1: "Other",
    2: "Network",
    3: "Group",
    4: "Remote (Out of Band) Management Communication Device",
    5: "External Environment",
    6: "Communication Channel",
    7: "PLDM Terminus",
    8: "Platform Event Log",
    9: "Device File",
    10: "Device File Directory",
    11: "Memory Rank",
    15: "Keypad",
    16: "Switch",
    17: "Pushbutton",
    18: "Display",
    19: "Indicator",
    30: "System Management Software",
    31: "System Firmware",
    32: "Operating System",
    33: "Virtual Machine Manager",
    34: "OS Loader",
    35: "Device Driver",
    36: "Management Controller",
    45: "System chassis (main enclosure)",
    46: "Sub-chassis",
    47: "Disk Drive Bay",
    48: "Peripheral Bay",
    49: "Device Bay",
    50: "Door",
    51: "Access Panel",
    52: "Cover",
    60: "Board",
    61: "Card",
    62: "Module",
    63: "System management module",
    64: "System board",
    65: "Memory board",
    66: "Memory module",
    67: "Processor module",
    68: "Add-in card",
    69: "Chassis front panel board",
    70: "Back panel board",
    71: "Power management/power distribution board",
    72: "Power system board",
    73: "Drive backplane",
    74: "System internal expansion board",
    75: "Other system board",
    76: "Chassis back panel board",
    77: "Processing blade",
    78: "Connectivity switch ",
    79: "Processor/memory module",
    80: "I/O module",
    81: "Processor/ I/O module",
    90: "Cooling device",
    91: "Cooling subsystem",
    92: "Cooling unit/domain",
    93: "Fan",
    94: "Peltier Cooling Device",
    95: "Liquid Cooling Device",
    96: "Liquid Cooling subsystem",
    105: "Other storage device",
    106: "Floppy Drive",
    107: "Fixed Disk / Hard Drive",
    108: "CD Drive",
    109: "CD/DVD Drive",
    110: "Other Silicon Storage Device",
    111: "Solid State Drive",
    120: "Power supply",
    121: "Battery",
    122: "Super capacitor",
    123: "Power converter",
    124: "DC-DC converter",
    125: "AC mains power supply",
    126: "DC mains power supply",
    127: "Voltage regulator",
    128: "Multi-rail Voltage regulator",
    129: "Multi-rail Voltage regulator channel",
    135: "0x03 Processor",
    136: "Chipset component",
    137: "Management controller",
    138: "Peripheral controller",
    139: "SEEPROM",
    140: "NVRAM chip",
    141: "FLASH Memory chip",
    142: "Memory chip",
    143: "Memory controller",
    144: "Network controller",
    145: "I/O controller",
    146: "South bridge",
    147: "Real Time Clock (RTC)",
    148: "FPGA/CPLD configurable logic device",
    149: "Accelerator",
    150: "TPM",
    151: "Subprocessor/Processor-Core",
    152: "GPU",
    153: "DPU",
    160: "Other Bus",
    161: "System Bus",
    162: "I2C Bus",
    163: "SMBus Bus",
    164: "SPI Bus",
    165: "PCI Bus",
    166: " PCI Express™ Bus including CXL",
    167: "PECI Bus",
    168: "LPC Bus",
    169: "USB Bus",
    170: "FireWire Bus",
    171: " SCSI Bus (parallel)",
    172: " SATA/SAS Bus",
    173: " Processor/front-side Bus",
    174: "Inter-processor Bus",
    175: "Inter-Accelerator link",
    185: "Connector",
    186: "Slot",
    187: "Cable (electrical or optical)",
    188: "Interconnect",
    189: "Plug",
    190: "Socket",
    200: "RJ45",
    201: "XFP",
    202: "SFP (SFF-8079)",
    203: "SFP10 (SFF-8083)",
    205: "SFP16 (SFF-8081)",
    206: "SFP28 (SFF-8402)",
    207: "SFP+ (SFF-8432)",
    208: "SFPDD",
    209: "CSFP",
    210: "QSFP (INF-8438i)",
    211: "QSFP28 (SFF-8665)",
    212: "QSFP+ (SFF-8436)",
    213: "QSFPDD (INF-8628)",
    214: "OSFP",
    215: "DSFP",
    300: "Ethernet",
    301: "InfiniBand",
    302: "Fibre Channel",
    303: "Omnipath"
}
